# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

r_github_packages:
  - jimhester/lintr

r:
- devel

before_install:
- Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0) install.packages("devtools")'
- Rscript -e 'devtools::install_deps()'

after_success:
- Rscript -e 'covr::codecov(type = "all")'
- Rscript -e 'source("tests/testthat/helper_lint.R")'
- Rscript -e 'lintr::lint_package(linters = linters)'

notifications:
  slack:
    on_success: change
    on_failure: change
